apiVersion: v1
kind: Service
metadata:
  name: vprocache01  # The name of the service
spec:
  selector:
    app: vpromc  # This selector matches pods with the label app: vpromc
  ports:
    - protocol: TCP
      port: 11211  # The port the service exposes within the cluster
      targetPort: 11211  # The port on the container that traffic is forwarded to
  type: ClusterIP  # This service type makes the service accessible only within the cluster